### ISSUE TITLE
能否新增支持滑动到底部自动加载的功能？

### ISSUE THREAD

**Issue by ehaahe** [lynnchurch/PullToRefresh#1]
能否新增支持滑动到底部时自动加载的功能？

**Comment by ByteRax** [comment]
+1

**Comment by ycpbyht** [comment]
原生都支持这个方法啊。
判断当前显示的item是不是最后一个，是的话自动加载。写一个方法放那就行了

**Comment by AI888Wealth** [comment]
@ehaahe @tanranran @ycpbyht 前段时间太忙了，不好意思，现在已增加滑动底部时自动加载的功能
