### ISSUE TITLE
滑动到底部自动加载的功能

### ISSUE THREAD

**Issue by Stevenxin** [lynnchurch/PullToRefresh#6]
这个只能在RecyclerView实现滑到底部自动加载更多的功能吗？Demo里没有其他比如listview的实现效果，而且在这个RecyclerView中是以RecyclerView.Adapter实现的自动加载，其他的listview怎么办。
本人修改以前的老项目，不是pulltorefresh就是自定义的listview

**Comment by AI888Wealth** [comment]
listview可以利用addFooterView()进行实现，原理与RecyclerView的实现差不多

**Comment by AI888Wealth** [comment]
这个https://github.com/lynnchurch/SwipeRefreshPlusLayout 应该能满足你的需求
